require:
  - rubocop-rspec
  - rubocop-rails
  
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'db/**/*'
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
  
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    
RSpec/MultipleExpectations:
  Max: 3

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    
Rails/OutputSafety:
  Enabled: false

Lint/MissingSuper:
  Enabled: false