default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('DB_HOST') { 'postgres' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

development:
  <<: *default
  database: _development

test:
  <<: *default
  database: _test

production:
  <<: *default
  database: _production
